name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: swift-codecov
      uses: mattpolzin/swift-codecov-action@0.3.0

